CREATE TABLE IF NOT EXISTS home (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title TEXT NOT NULL,
  subtitle TEXT NOT NULL,
  description TEXT NOT NULL,
  primary_button_text TEXT NOT NULL,
  primary_button_link TEXT NOT NULL,
  secondary_button_text TEXT,
  secondary_button_link TEXT,
  image_url TEXT,
  about_title TEXT NOT NULL,
  about_description TEXT NOT NULL,
  about_card_title TEXT NOT NULL,
  about_card_description TEXT NOT NULL,
  highlights_title TEXT NOT NULL,
  highlights_description TEXT NOT NULL,
  highlights TEXT NOT NULL,
  is_active INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);